### ISSUE TITLE
Each entry in /etc/rhsm/rhsm.conf should be a configurable param

### ISSUE THREAD

**Issue by bbriggs** [voxpupuli/puppet-rhsm#11]

**Comment by tux-o-matic** [comment]
Some of those settings (like cert path) might be hardcoded in RedHat/YUM so I'm not sure there is value in making everything configurable in it. 
I can see a potential for things like check intervals.

**Comment by kallies** [comment]
@bbriggs what usecase do you have in mind? Depending on this I see (at least) three options

* Using puppetlabs-inifile and use a hash to add configuration parameters
* Update the template to support more/all parameters (see `subscription-manager config --help`)
* Use `subscription-manager config` as a provider instead of the static rhsm.conf (may be overkill though)

**Comment by bbriggs** [comment]
You know, I opened this over a year and a half ago so I don't really remember exactly anymore. I _do_ remember having to fight with RHSM and add an extra tweak to the file with an additional manifest to make it work like I needed it, but that feels like it was in another life now ;)

**Comment by kallies** [comment]
I just compared an RHSM and an Satellite 6 registered host. The main differences I see there are

```
prefix = /rhsm
# vs. /subscription
repo_ca_cert = %(ca_cert_dir)skatello-server-ca.pem
# vs. %(ca_cert_dir)sredhat-uep.pem
full_refresh_on_yum = 1
# vs. 0
certCheckInterval = 480
# modified check in interval, vs. 240
```
